### ISSUE TITLE
Color regions names should fall back to parent values

### ISSUE THREAD

**Issue by coldino** [arkutils/Purlovia#59] opened 2019-08-03 17:52 UTC
For example with the Giganotosaurus we have color names for the base species, but these are not picked up by the bosses based on it.

Step up the inheritance chain looking for the first one with region names and use those.

@cadon can you see any issue with this plan?

**Comment by cadon** [comment] 2019-08-03 20:57
sounds good for me.

**Comment by alex4401** [comment] 2020-04-13 21:27
#90 is a duplicate of this issue, but covers a wider field.

**Closed by alex4401** 2020-04-13 21:27 UTC
